spring:
  #redis缓存配置
  redis:
    #连接的redis数据库
    database: 0
    #服务器地址
    host: 192.168.171.100
    #密码
    #password: p@ssw0rd
    #端口
    port: 6379
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 50
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 10
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: 10ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 1000ms